### ISSUE TITLE
GeneratedPluginRegistrant.m: "Module 'raw_sound' not found" 

### ISSUE THREAD

**Issue by chipweinberger** [8fdafs2/flutter_raw_sound#4]
First time trying to use this plugin, thanks for making it!!

Not sure where to start with this issue.

```
/Volumes/User/MBP/flutter_test_app/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'raw_sound' not found
@import raw_sound;
 ~~~~~~~^~~~~~~~~
1 error generated.
```

<img width="689" alt="Screen Shot 2022-02-17 at 3 48 49 PM" src="https://user-images.githubusercontent.com/1863934/154590809-18e79b59-4b63-43cd-aeff-021ff1b7206b.png">

pubspec.yaml

>  ...
>
> dependencies:
>   flutter:
>     sdk: flutter
> 
>   cupertino_icons: ^1.0.2
>   raw_sound: ^0.3.0+1
>
>   ...

**Comment by chipweinberger** [comment]
I'm trying to compile the example app: https://pub.dev/packages/raw_sound/example

Flutter: 2.10.1

**Comment by chipweinberger** [comment]
```
charlesweinberger@Chips-Macbook-Pro-2 jamcorder_flutter_app % flutter run
Multiple devices found:
ChipsiPhone (mobile) • 00008101-000A0D1E3C90001E            • ios            • iOS
15.3.1 19D52
iPhone 13 (mobile)   • FF7C845F-340A-4611-BF36-E93C8E838C71 • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
Chrome (web)         • chrome                               • web-javascript • Google
Chrome 98.0.4758.102
[1]: ChipsiPhone (00008101-000A0D1E3C90001E)
[2]: iPhone 13 (FF7C845F-340A-4611-BF36-E93C8E838C71)
[3]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 2
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...                                             784ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `raw_sound` from `.symlinks/plugins/raw_sound/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because
      checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "raw_sound":
      In Podfile:
        raw_sound (from `.symlinks/plugins/raw_sound/ios`)

    Specs satisfying the `raw_sound (from `.symlinks/plugins/raw_sound/ios`)` dependency
    were found, but they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in
    `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in
    `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in
    `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in
    `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in
    `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in
    `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in
    `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in
    `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in
    `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1
    078:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in
    `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1
    076:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1
    24:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in
    `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in
    `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in
    `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in
    `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in
    `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:i
    n `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 13.
```

**Comment by chipweinberger** [comment]
Solved it:

**flutter_app/ios/Podfile**

`platform :ios, '10'` changed to `platform :ios, '15.2'`,

**Comment by lukepighetti** [comment]
`14` should also work, for what it's worth
